name: Test laravel projects

on:
  push:
    branches: [master]
    paths:
      - '**.php'
      - '**.stubphp'
      - 'composer.json'
      - 'tests/laravel*'
      - '.github/workflows/test-laravel.yml'
  pull_request:
    paths:
      - '**.php'
      - '**.stubphp'
      - 'composer.json'
      - 'tests/laravel*'
      - '.github/workflows/test-laravel.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Test Laravel

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test Laravel
      run: |
        ./tests/Application/laravel-test.sh
